version: '3.7'

services:
    app:
        container_name: '${APP_NAME}-Backend'
        build:
            context: '.'
            args:
                NODE_VERSION: ${NODE_VERSION}
        depends_on:
            - postgres
            - redis
        ports:
            - '${EXPRESS_PORT}:${EXPRESS_PORT}'
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - ./error.log:/usr/src/app/error.log
        networks:
            - backend
        restart: always

    redis:
        image: redis:latest
        container_name: '${APP_NAME}-Redis'
        hostname: ${REDIS_HOST}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        volumes:
            - './docker/db/redis:/data'
        networks:
            - backend
        restart: always

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: '${APP_NAME}-RedisCommander'
        depends_on:
            - redis
        ports:
            - '8081:8081'
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
        networks:
            - backend
        restart: always

networks:
    backend:
