version: '3.8'

services:
    app:
        container_name: '${APP_NAME}-Backend'
        build:
            context: '.'
            args:
                NODE_VERSION: ${NODE_VERSION}
        depends_on:
            - redis
            - mysql
        ports:
            - '${EXPRESS_PORT}:${EXPRESS_PORT}'
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
            - ./error.log:/usr/src/app/error.log
        networks:
            - backend
        restart: always

    redis:
        image: redis:latest
        container_name: '${APP_NAME}-Redis'
        hostname: ${REDIS_HOST}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        volumes:
            - './docker/db/redis:/data'
        networks:
            - backend
        restart: always

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: '${APP_NAME}-RedisCommander'
        depends_on:
            - redis
        ports:
            - '${RCOMM_PORT}:${RCOMM_PORT}'
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
        networks:
            - backend
        restart: always

    mysql:
        image: mysql:latest
        container_name: '${APP_NAME}-MySQL'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '${DB_PORT}:${DB_PORT}'
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_HOST=${DB_HOSTNAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - './docker/db/mysql:/var/lib/mysql'
        networks:
            - backend
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: '${APP_NAME}-PHPMyAdmin'
        ports:
            - '${PMA_PORT}'
        environment:
            - PMA_HOST=${DB_HOSTNAME}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PHP_UPLOAD_MAX_FILESIZE=100MB
        depends_on:
            - mysql
        networks:
            - backend
        restart: always

networks:
    backend:
